server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tiezhuliu/wanchengke.git
          searchPaths: config
          username: m18813933843@163.com
          password: wyytxmlwclybq
      label: master
eureka:
  client:
    serviceUrl:
      dafaultZone: http://loaclhost:8061/eureka/