server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/
zuul:                          #本身也自带负载均衡    一般都是配合Ribbon（Netflix发布的负载均衡器）来实现
  routes:
    provider: /p/**            #给服务提供者provider设置映射，请求包含p/就是拦截针对provider服务的请求
#  host:
#    connect-timeout-millis: 3000
#    socket-timeout-millis: 3000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeout-in-milliseconds: 3000
ribbon:                           #添加ribbon的超时时间设置,不然会报com.netflix.zuul.exception.ZuulException: Forwarding error（超时错误）
  ReadTimeout: 3000
  ConnectTimeout: 3000