server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/
feign:
  hystrix:
    enabled: true             #是否开启 hystrix 熔断器